spring:
  main:
    allow-bean-definition-overriding: false
  application:
    name: clean-city
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clean-city}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
    schema: ${DB_SCHEMA:clean_city}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  security:
    jwt:
      secret: ${JWT-SECRET:oratoroeuaroupadoreideromaporcausadoalokqueestavatocandoforronatomorrowlanddeitu}
      expiration: ${JWT-EXPIRATION:86400000}
server:
  port: 8080
  servlet:
    context-path: /clean-city

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

